# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
pr:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: sauce_user
  value: $(SAUCE_USERNAME)
- name: sauce_key
  value: $(SAUCE_ACCESS_KEY) 

steps:
- bash: echo $SAUCE_USER
- bash: echo $SAUCE_KEY
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
